name: Deploy with OpenTofu

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        run: |
          # Detener los servicios de Docker
          sudo systemctl stop docker
          sudo systemctl stop containerd
          sudo systemctl stop docker.socket
          
          # Desinstalar Docker y sus dependencias
          sudo apt-get purge -y docker.io docker-ce docker-ce-cli containerd.io
          
          # Eliminar directorios y archivos relacionados con Docker
          sudo rm -rf /var/lib/docker
          sudo rm -rf /etc/docker
          sudo rm -rf /var/run/docker
          
          # Eliminar containerd
          sudo apt-get purge -y containerd
          sudo rm -rf /etc/containerd
          sudo rm -rf /var/lib/containerd
          
          # Actualizar la caché de APT
          sudo apt-get update
          
          # Instalar Docker
          sudo apt-get install -y docker.io
          
          # Iniciar el servicio de Docker
          sudo systemctl start docker
          
          # Agregar el usuario al grupo docker
          sudo usermod -aG docker $USER
          newgrp docker
          
          # Verificar la instalación
          docker --version
          docker info
    
      - name: Install OpenTofu
        run: |
          # Instalar OpenTofu usando snap
          sudo snap install --classic opentofu
          tofu --version

      - name: Install kubectl and Minikube
        run: |
          # Kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

          # Minikube
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

          # Configuración especial para CI
          export MINIKUBE_IN_STYLE=false
          export CHANGE_MINIKUBE_NONE_USER=true
          minikube start --driver=docker --force --wait=all
          minikube update-context

          # Verificación
          kubectl cluster-info
          minikube status

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          minikube kubectl -- config view --flatten > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Terraform Init
        run: tofu init

      - name: Terraform Apply
        run: tofu apply -auto-approve

      - name: Verify Deployment
        run: |
          kubectl get all -A
          minikube service list --url
