name: Deploy with OpenTofu

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check preinstalled Docker
        run: |
          docker --version
          docker info
          groups # Verifies if the runner user is in the docker group

      - name: Install OpenTofu
        run: |
          # Instalar OpenTofu usando snap
          sudo snap install --classic opentofu
          tofu --version

      - name: Install kubectl and Minikube
        run: |
          # Kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

          # Minikube
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

          # Configuración especial para CI
          export MINIKUBE_IN_STYLE=false
          export CHANGE_MINIKUBE_NONE_USER=true
          minikube start --driver=docker --force --wait=all

          # Esperar a que el cluster de Minikube esté listo y el contexto se actualice
          echo "Esperando a que Minikube esté completamente listo y el contexto se actualice..."
          for i in $(seq 1 20); do # Aumentamos el número de intentos
            minikube update-context
            # Verificar si el contexto actual está establecido y no está vacío
            CURRENT_CONTEXT=$(kubectl config current-context 2>/dev/null)
            if [ -n "$CURRENT_CONTEXT" ]; then # -n comprueba si la cadena no está vacía
              echo "Minikube está listo y el contexto '$CURRENT_CONTEXT' está establecido."
              break
            fi
            echo "Minikube no está listo aún o el contexto no está establecido, reintentando en 5 segundos..."
            sleep 5
          done
          
          # Si después de los intentos el contexto no está, fallar explícitamente
          CURRENT_CONTEXT=$(kubectl config current-context 2>/dev/null)
          if [ -z "$CURRENT_CONTEXT" ]; then
            echo "Error: Minikube no pudo establecer el contexto de Kubernetes después de múltiples intentos."
            exit 1
          fi

          # Verificación final
          kubectl cluster-info
          minikube status

      - name: Setup Kubeconfig
        run: |
          echo "Current HOME directory: $HOME"
          echo "Ensuring .kube directory exists at $HOME/.kube"
          mkdir -p "$HOME/.kube"
          echo "Generating Kubeconfig at $HOME/.kube/config"
          # Usamos 'minikube kubectl --' para asegurar que se usa el kubectl de minikube
          minikube kubectl -- config view --flatten > "$HOME/.kube/config"
          echo "Setting permissions for $HOME/.kube/config"
          chmod 600 "$HOME/.kube/config"
          echo "Kubeconfig content:"
          cat "$HOME/.kube/config"
          echo "Verifying Kubeconfig with Kubectl:"
          # Usamos KUBECONFIG explícitamente para todas las llamadas a kubectl
          KUBECONFIG="$HOME/.kube/config" kubectl config current-context
          KUBECONFIG="$HOME/.kube/config" kubectl cluster-info
          KUBECONFIG="$HOME/.kube/config" kubectl get nodes

      - name: Terraform Init
        run: tofu init

      - name: Terraform Apply
        env:
          KUBECONFIG: ${{ runner.homedir }}/.kube/config
          TF_LOG: DEBUG # Mantenlo para obtener logs detallados
        run: tofu apply -auto-approve

      - name: Verify Deployment
        run: |
          kubectl get all -A
          minikube service list --url
